/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_phash_AudioData */

#ifndef _Included_org_phash_AudioData
#define _Included_org_phash_AudioData

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_phash_AudioData
 * Method:    readAudio
 * Signature: (Ljava/lang/String;IFLorg/phash/AudioMetaData;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_phash_AudioData_readAudio
  (JNIEnv *, jclass, jstring, jint, jfloat, jobject);


#endif

